# Generated by Django 2.0.2 on 2018-04-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multicastGroup', models.CharField(max_length=15)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=64, null=True)),
                ('feedName', models.CharField(blank=True, max_length=64, null=True)),
                ('feedType', models.CharField(blank=True, max_length=64, null=True)),
                ('sessionName', models.CharField(blank=True, max_length=256, null=True)),
                ('connectionType', models.CharField(blank=True, max_length=64, null=True)),
                ('channel', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lastEdited', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IGMPSnoopingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multicastGroup', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switchIP', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('protocol', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('model', models.CharField(max_length=64)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='interfacedescription',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.Server'),
        ),
        migrations.AddField(
            model_name='igmpsnoopinggroup',
            name='interfaces',
            field=models.ManyToManyField(to='marketdata.InterfaceDescription'),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.InterfaceDescription'),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='multicastGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.IGMPSnoopingGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='interfacedescription',
            unique_together={('switchIP', 'description')},
        ),
    ]
