# Generated by Django 2.0.2 on 2018-04-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacedescription',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='interfacedescription',
            name='protocol',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='interfacedescription',
            name='status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
