# Generated by Django 2.0.2 on 2018-04-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_auto_20180419_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacedescription',
            name='interface',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='interfacedescription',
            name='line',
            field=models.CharField(default=1000, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interfacedescription',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='interfacedescription',
            unique_together={('switchIP', 'interface')},
        ),
    ]
