# Generated by Django 2.0.2 on 2018-04-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_feed_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacedescription',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdata.Server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdata.Customer'),
        ),
    ]
