# Generated by Django 2.0.2 on 2018-04-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_auto_20180420_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
