# Generated by Django 2.0.2 on 2018-04-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0007_auto_20180420_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessrecord',
            unique_together=set(),
        ),
    ]
