# Generated by Django 2.0.2 on 2018-04-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0008_auto_20180420_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessrecord',
            unique_together={('interface', 'multicastGroup', 'created')},
        ),
    ]
