# Generated by Django 2.0.2 on 2018-04-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0009_auto_20180420_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='month',
            field=models.CharField(default='04', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='year',
            field=models.CharField(default='2018', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='accessrecord',
            unique_together={('interface', 'multicastGroup', 'year', 'month')},
        ),
    ]
