# Generated by Django 2.0.2 on 2018-04-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0010_auto_20180420_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='channel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
