# Generated by Django 2.0.2 on 2018-06-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0011_auto_20180421_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.InterfaceDescription')),
                ('multicastGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.IGMPSnoopingGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyaccessrecord',
            unique_together={('interface', 'multicastGroup', 'year', 'month', 'day')},
        ),
    ]
